export const states = [
  "Punjab",
  "Uttar Pradesh (East)",
  "Manipur",
  "Nagaland",
  "Arunachal Pradesh",
  "Uttarakhand",
  "Madhya Pradesh",
  "Uttar Pradesh (West)",
];

export const districts = [
  "Mainpuri",
  "Etah",
  "Firozabad",
  "Kasganj",
  "Aligarh",
  "Agra",
  "Auraiya",
  "Etawah",
  "Amritsar",
  "AMRITSAR",
  "Barnala",
  "BARNALA",
  "BATHINDA",
  "Bathinda",
  "Bhatinda",
  "Faridkot",
  "FARIDKOT",
  "Fatehgarh Sahib",
  "Fazilka",
  "FAZILKA",
  "Firozpur",
  "Gurdaspur",
  "Hoshiarpur",
  "Jalandhar",
  "JALANDHAR",
  "Kapurthala",
  "Ludhiana",
  "LUDHIANA",
  "Mansa",
  "MANSA",
  "Moga",
  "Muktsar Sahib",
  "Pathankot",
  "PATHANKOT",
  "Patiala",
  "PATIALA",
  "Rupnagar",
  "RUPNAGAR",
  "S.A.S NAGAR",
  "S.A.S. Nagar",
  "Sangrur",
  "SANGRUR",
  "SBS Nagar",
  "Sri Muktsar Sahib",
  "Tarn Taran",
  "TARN TARAN",
  "AMETHI",
  "Ayodhya",
  "Barabanki",
  "BARABANKI",
  "BHADOHI",
  "CHANDAULI",
  "Farrukhabad",
  "FARRUKHABAD",
  "GHAZIPUR",
  "JAUNPUR",
  "Kanpur Dehat",
  "KANPUR DEHAT",
  "KAUSHAMBI",
  "MIRZAPUR",
  "PRATAPGARH",
  "PRAYAGRAJ",
  "RAE BARELI",
  "SHAHJAHANPUR",
  "SONBHADRA",
  "SULTANPUR",
  "Unnao",
  "VARANASI",
  "Bishnupur",
  "Jiribam",
  "Kangpokpi",
  "Chandel",
  "Ukhrul",
  "Noney",
  "Imphal West",
  "Imphal East",
  "Churachandpur",
  "Kakching",
  "Kamjong",
  "Thoubal",
  "Tengnoupal",
  "Senapati",
  "Tamenglong",
  "Pherzawl",
  "Mon",
  "Niuland",
  "Zunheboto",
  "Peren",
  "Wokha",
  "Kohima",
  "Mokokchung",
  "Tuensang",
  "Shamator",
  "Phek",
  "Chumoukedima",
  "Tseminyu",
  "Dimapur",
  "Kiphire",
  "Longleng",
  "Meluri",
  "Noklak",
  "West Siang",
  "Dibang Valley",
  "Papum Pare",
  "East Kameng",
  "Tirap",
  "Upper Subansiri",
  "Leparada",
  "East Siang",
  "Siang",
  "Changlang",
  "Anjaw",
  "Kra Daadi",
  "Namsai",
  "Lower Dibang Valley",
  "Kurung Kumey",
  "West Kameng",
  "Upper Siang",
  "Lower Siang",
  "Kamle",
  "Lower Subansiri",
  "Tawang",
  "Longding",
  "Shi Yomi",
  "Pakke Kessang",
  "Lohit",
  "ALMORA",
  "CHAMOLI",
  "NAINITAL",
  "BAGESHWAR",
  "PAURI GARHWAL",
  "UDAM SINGH NAGAR",
  "CHAMPAWAT",
  "DEHRADUN",
  "HARIDWAR",
  "PITHORAGARH",
  "RUDRA PRAYAG",
  "TEHRI GARHWAL",
  "UTTAR KASHI",
  "ASHOKNAGAR",
  "BETUL",
  "BHIND",
  "CHHATARPUR",
  "Dadra Nagar Haveli",
  "DAMAN",
  "DIU",
  "GUNA",
  "HOSHANGABAD",
  "INDORE",
  "KATNI",
  "KHARGONE",
  "NARSINGHPUR",
  "Niwari",
  "NIWARI",
  "PANNA",
  "Panna",
  "RAISEN",
  "RAJGARH",
  "Rajgarh",
  "SATNA",
  "SEHORE",
  "SEONI",
  "SHAHDOL",
  "Shivpuri",
  "SIDHI",
  "SINGRAULI",
  "UJJAIN",
  "UMARIA",
  "VIDISHA",
  "TIKAMGARH",
  "JHABUA",
  "JABALPUR",
];

export const blocks = [
  "Jageer",
  "Awagarh",
  "Nidhauli Kalan",
  "Eka",
  "Hathwant",
  "Jasrana",
  "Bewar",
  "Ghiror",
  "AMANPUR",
  "SIDHPURA",
  "GANJ DUNDWARA",
  "Iglas",
  "Bichpuri",
  "Pinahnat",
  "Mainpuri",
  "Jagner",
  "Saiyan",
  "Karhal",
  "Erwa Katra",
  "Mahewa",
  "Kuraoli",
  "Chogawan",
  "Jandiwala Guru",
  "Ajnala",
  "ATTARI",
  "RAYYA",
  "MAJITHA",
  "TARSIKKA",
  "VERKA",
  "MEHAL KALAN",
  "BARNALA",
  "SEHNA",
  "PHUL",
  "BHAGTA BHAIKA",
  "NATHANA",
  "GONIANA",
  "MAUR",
  "SUDHAR",
  "Maloud",
  "TALWANDI SABO",
  "BATHINDA",
  "RAMPURA",
  "SANGAT",
  "KOT KAPURA",
  "FARIDKOT",
  "JAITU",
  "Khera",
  "Bassi Pathana",
  "Amloh",
  "Sirhind",
  "Khamano",
  "FAZILKA",
  "KHUIAN SARWAR",
  "ABOHAR",
  "Arniwala Shiekh Subhan",
  "JALALABAD",
  "Makhu",
  "Mamdot",
  "Ghall Khurd",
  "Guru Har Sahai",
  "FIROZPUR",
  "ZIRA",
  "Dorangla",
  "Dera Baba Nanak",
  "Dhariwal",
  "Qadian",
  "Gurdaspur",
  "BATALA",
  "FATEHGARH CHURIAN",
  "KALANAUR",
  "SRI HARGOBINDPUR",
  "KAHNUWAN",
  "DINANAGAR",
  "Hajipur",
  "GARHSHANKAR",
  "TANDA",
  "HOSHIARPUR-I",
  "HOSHIARPUR-II",
  "MAHILPUR",
  "BHUNGA",
  "DASUYA",
  "MUKERIAN",
  "TALWARA",
  "ShahKot",
  "Jalandhar - West",
  "JALANDHAR-EAST",
  "Nurmahal",
  "Phillaur",
  "Rurka Kalan",
  "LOHIAN",
  "BHOGPUR",
  "NAKODAR",
  "MEHATPUR",
  "Dhilwan",
  "Nadala",
  "Sultanpur Lodhi",
  "KAPURTHALA",
  "PHAGWARA",
  "SIDHWAN BET",
  "PAKHOWAL",
  "RAIKOT",
  "DORAHA",
  "LUDHIANA-2",
  "KHANNA",
  "SAMRALA",
  "LUDHIANA-1",
  "MACHHIWARA",
  "JAGRAON",
  "DEHLON",
  "Budhlada",
  "MANSA",
  "BHIKHI",
  "JHUNIR",
  "SARDULGARH",
  "Nihal Singh Wala",
  "BAGHAPURANA",
  "MOGA-I",
  "MOGA-II",
  "Kot-Ise-Khan",
  "MALOUT",
  "LAMBI",
  "GIDDERBAHA",
  "PATHANKOT",
  "GHAROTA",
  "DHARKALAN",
  "SUJANPUR",
  "BAMIAL",
  "NAROT JAIMAL SINGH",
  "Sanour",
  "GHANAUR",
  "RAJPURA",
  "SAMANA",
  "BHUNERHERI",
  "NABHA",
  "PATRAN",
  "SHAMBHU KALAN",
  "PATIALA",
  "PATIALA RURAL",
  "Anandpur Sahib",
  "Nurpur Bedi",
  "RUPNAGAR",
  "MORINDA",
  "DERA BASSI",
  "Kharar",
  "Majri",
  "Sunam",
  "Dhuri",
  "Leheraganga",
  "Andana",
  "Ahmedgarh",
  "Malerkotla H",
  "Bhawani Garh",
  "SANGRUR",
  "SHERPUR",
  "DIRBA",
  "BALACHAUR",
  "NAWANSHAHR",
  "AUR",
  "BANGA",
  "SAROYA",
  "Muktsar",
  "Bhikhi Wind-13",
  "GANDIWIND-9",
  "KHADUR-SAHIB-10",
  "CHOHLA SAHIB-8",
  "Patti-14",
  "Tarn Taran-12",
  "Valtoha-15",
  "NAUSHEHRA PANNUAN-11",
  "BAHADURPUR",
  "AMETHI",
  "BHETUA",
  "JAGDISHPUR",
  "MUSAFIR KHANA",
  "BHADAR",
  "JAMO",
  "SANGRAMPUR",
  "SHUKUL BAZAR",
  "SINGHPUR",
  "TILOI",
  "MAYA BAZAR",
  "MASAULI",
  "FATEHPUR",
  "BANKI",
  "HARAKH",
  "SIDHAUR",
  "ABHAULI",
  "GYANPUR",
  "SURIYAVAN",
  "AURAI",
  "BHADOHI",
  "CHANDAULI",
  "NAUGARH",
  "BERAHANI",
  "CHAHNIYA",
  "CHAKIYA",
  "DHANAPUR",
  "NIYAMATABAD",
  "SAHABGANJ",
  "SAKALDIHA",
  "NAWABGANJ",
  "KAMALGANJ",
  "SHAMSABAD",
  "JAKHANIA",
  "KASIMABAD",
  "MARDAH",
  "BHADAURA",
  "BHANWARKOL",
  "DEVKALI",
  "GHAZIPUR",
  "KARANDA",
  "MANIHARI",
  "REVATIPUR",
  "SADAT",
  "SAIDPUR",
  "VARACHAKWAR",
  "ZAMANIA",
  "JALAL PUR",
  "RAM NAGAR",
  "BADLA PUR",
  "BAKSHA",
  "BARASATHI",
  "DHARMA PUR",
  "DOBHI",
  "KARANJA KALA",
  "KERAKAT",
  "KHUTHAN",
  "MACHCHALI SHAHAR",
  "MAHARAJ GANJ",
  "MARIYAHU",
  "MUFTI GANJ",
  "MUNGRA BADSHAH PUR",
  "RAM PUR",
  "SHAH GANJ",
  "SIKRARA",
  "SIRKONI",
  "SUITHA KALA",
  "SUJAN GANJ",
  "RAJPUR",
  "MAITHA",
  "CHAIL",
  "MANJHANPUR",
  "NEVADA",
  "SIRATHU",
  "KARA",
  "KAUSHAMBI",
  "MOORATGANJ",
  "SARSAWAN",
  "CHHANVEY",
  "KON",
  "MAJHAWA",
  "NAGAR (CITY)",
  "SHIKHAR",
  "HALLIA",
  "JAMALPUR",
  "NARAINPUR",
  "PATEHRA",
  "RAJGARH",
  "LALGANJ",
  "PAHARI",
  "SHIVGARH",
  "ASPUR DEOSARA",
  "BABA BELKHARNATH DHAM",
  "BABAGANJ",
  "KUNDA",
  "BIHAR",
  "GAURA",
  "KALAKANKAR",
  "LAKSHAMANPUR",
  "MAGRAURA",
  "MANDHATA",
  "PATTI",
  "PRATAPGARH (SADAR)",
  "RAMPUR SANRAMGARH",
  "SANDWA CHANDRIKA",
  "SANGIPUR",
  "BAHRIA",
  "CHAKA",
  "DHANUPUR",
  "HANDIA",
  "HOLAGARH",
  "JASRA",
  "KARCHHANA",
  "KAUDHIYARA",
  "KAURIHAR",
  "KORAON",
  "MANDA",
  "MAUAIMA",
  "MEJA",
  "PHULPUR",
  "PRATAPPUR",
  "SAIDABAD",
  "SHANKARGARH",
  "SORAON",
  "URUWAN",
  "BHAGWATPUR",
  "SAHSON",
  "SRINGVERPUR DHAN",
  "MAHRAJGANJ",
  "AMAWAN",
  "BACHHARAWAN",
  "CHHATOH",
  "DALMAU",
  "DEEH",
  "DEENSHAH GAURA",
  "HARCHANDPUR",
  "JAGATPUR",
  "KHIRON",
  "RAHI",
  "ROHANIA",
  "SALON",
  "SARENI",
  "SATAON",
  "UNCHAHAR",
  "DADROL",
  "MIRZAPUR",
  "TILHAR",
  "CHATRA",
  "BABHANI",
  "CHOPAN",
  "DUDHI",
  "GHORAWAL",
  "KARMA",
  "KONE",
  "MYORPUR",
  "NAGWA",
  "ROBERTSGANJ",
  "KUREBHAR",
  "LAMBHUA",
  "AKHAND NAGAR",
  "BALDIRAI",
  "BHADAIYA",
  "DHANPATGANJ",
  "DOSTPUR",
  "JAISINGHPUR",
  "KARAUDIKALA",
  "KURWAR",
  "MOTIGARPUR",
  "P.P.KAMAICHA",
  "HASANGANJ",
  "AURAS",
  "CHIRAIGAON",
  "CHOLAPUR",
  "KASHI VIDYAPEETH",
  "Bishnupur",
  "Borobekra CD Block",
  "Bungte Chiru",
  "Chakpikarong",
  "Champhai",
  "Chandel",
  "Chingai",
  "Haochong",
  "Haorangsabal",
  "Heingang CD Block",
  "Henglep",
  "Hiyangthang",
  "Island",
  "Jessami Td",
  "Jiribam C D Block",
  "Kakching",
  "Kamjong",
  "Kangchup Geljang",
  "Kangpokpi",
  "Kangvai",
  "Kasom Khullen",
  "Keirao CD Block",
  "Khangbarol",
  "Khengjoy",
  "Khoupum",
  "Kshetrigao CD Block",
  "Lamka",
  "Lamka South",
  "Langmeidong",
  "Lanva",
  "Lhungtin",
  "Lilong CD Block",
  "Longmai",
  "Lungchong Meiphai",
  "Machi",
  "Moirang",
  "Moreh",
  "Mualnuam",
  "Nambol",
  "Nungba",
  "Paomata",
  "Patsoi",
  "Phaibung Khullen",
  "Phungyar",
  "Purul",
  "Sahamphung Td Block",
  "Saikot",
  "Saikul",
  "Saitu Gamphazol",
  "Samulamlan",
  "Sangaikot",
  "Sawombung CD Block",
  "Singngat",
  "Song Song",
  "Suangdoh",
  "Tadubi",
  "Tamei",
  "Tamenglong",
  "Tengnoupal",
  "Thanlon",
  "Thoubal",
  "Tipaimukh",
  "Tousem",
  "Tuibong",
  "T Vaichong",
  "Ukhrul",
  "Vangai Range",
  "Wangjing CD Block",
  "Wangoi",
  "Willong",
  "Aboi",
  "Aghunaqa",
  "Akuhaito",
  "Akuluto",
  "Angjangyang",
  "Athibung",
  "Bhandari",
  "Botsa",
  "Changpang",
  "Changtongya",
  "Chare",
  "Chen",
  "Chessore",
  "Chetheba",
  "Chiephobozou",
  "Chizami",
  "Chuchuyimlang",
  "Chukitong",
  "Chumukedima",
  "Chunlikha",
  "Dhansiripar",
  "East Dimapur",
  "Ghathashi",
  "Jakhama",
  "Jalukie",
  "Khonsa",
  "Kikruma",
  "Kiphire",
  "Kohima",
  "Kubolong",
  "Kuhuboto",
  "Longchem",
  "Longkhim",
  "Longleng",
  "Longmatra",
  "Mangkolemba",
  "Medziphema",
  "Meluri",
  "Mon",
  "Niuland",
  "Noklak",
  "Noksen",
  "Ongpangkong(North)",
  "Ongpangkong(South)",
  "Panso",
  "Peren",
  "Pfutsero",
  "Phek",
  "Phomching",
  "Pungro",
  "Ralan",
  "Sakshi",
  "Sangsangyu",
  "Sanis",
  "Satakha",
  "Satoi",
  "Sechu Zubza",
  "Sekruzu",
  "Shamator",
  "Sitimi",
  "Suruhoto",
  "Tamlu",
  "Tenning",
  "Thonoknyu",
  "Tizit",
  "Tobu",
  "Tokiye",
  "Tseminyu",
  "Tsurangkong",
  "Tuli",
  "Wakching",
  "West Dimapur",
  "Weziho",
  "Wokha",
  "Wozhuro-Ralan",
  "Zunheboto",
  "Along East",
  "Along West",
  "Anelih Arzu",
  "Anini-Mepi",
  "Bagra",
  "Balijan",
  "Bameng",
  "Bana",
  "Bari Basip",
  "Baririjo",
  "Basar",
  "Bilat",
  "Boleng",
  "Bordumsa",
  "Borduria",
  "Borum",
  "Chaglagam",
  "Chambang",
  "Changlang",
  "Chayangtajo",
  "Chetam",
  "Chowkham",
  "Dadam",
  "Dambuk",
  "Damin",
  "Daporijo",
  "Darak",
  "Daring",
  "Dirang",
  "Diyun",
  "Doimukh",
  "Dumporijo",
  "Etalin Malinye",
  "Gangte",
  "Geku",
  "Gensi",
  "Gepen",
  "Giba",
  "Hawai-Walong",
  "Hayuliang",
  "Hong-Hari",
  "Hunli-Kronli",
  "Jang-Thingbu",
  "Jengging",
  "Kalaktang",
  "Kamporijo",
  "Kangku",
  "Kantang",
  "Kanubari",
  "Kaying",
  "Khagam-Miao",
  "Khenewa",
  "Khimiyang",
  "Khonsa",
  "Kimin",
  "Kitpi",
  "Koloriang",
  "Lada",
  "Lawnu",
  "Lazu",
  "Lekang",
  "Likabali",
  "Limeking",
  "Liromoba-Yomcha",
  "Lumla",
  "Manchal",
  "Manigoan",
  "Manmao",
  "Mariyang",
  "Mebo",
  "Mechuka-Tato",
  "Mengio",
  "Mukto Bongkhar",
  "Nacho",
  "Nafra",
  "Nampong",
  "Namsai",
  "Namsang",
  "Niausa",
  "Nyapin",
  "Pakkekessang",
  "Palin",
  "Pangin",
  "Paniasang",
  "Parsiparlo",
  "Pasighat",
  "Payeng",
  "Payum",
  "Persin Dollungmukh",
  "Phassang",
  "Pipsorang",
  "Pipu",
  "Pistana",
  "Polosang",
  "Pongchau",
  "Puchi Geko",
  "Ramle Bango",
  "Rebo Parging",
  "Riga",
  "Roing",
  "Ruksin",
  "Rumgong",
  "Sagalee",
  "Sangram",
  "Sarli",
  "Sawa",
  "Seijosa",
  "Seppa",
  "Singa Gelling",
  "Singchung",
  "Siyum",
  "Taksing",
  "Tali",
  "Taliha",
  "Tamen-Raga",
  "Tawang",
  "Tezu",
  "Thrizino",
  "Tirbin",
  "Tuting",
  "Vijoynagar",
  "Wakka",
  "Wakro",
  "Yangte",
  "Yatdam",
  "Yingkiong",
  "Zemithang Dudunghar",
  "Ziro-I",
  "Ziro-Ii",
  "DWARAHAT",
  "TARIKHET",
  "THARALI",
  "BHAISIYA CHHANA",
  "BHIKIYASAIN",
  "HALDWANI",
  "CHAUKHUTIYA",
  "DHAULADEVI",
  "LAMGARA",
  "SULT",
  "SYALDEY",
  "BAGESHWAR",
  "THALISAIN",
  "GADARPUR",
  "DASHOLI",
  "RUDRAPUR",
  "HAWALBAG",
  "TAKULA",
  "GARUR",
  "KARNAPRAYAG",
  "NARAYANBAGAR",
  "POKHARI",
  "KAPKOTE",
  "BARAKOT",
  "PATI",
  "GAIRSAIN",
  "CHAMPAWAT",
  "CHAKRATA",
  "DOIWALA",
  "RAIPUR",
  "SAHASPUR",
  "VIKASNAGAR",
  "KALSI",
  "BAHADRABAD",
  "BHAGWANPUR",
  "KHANPUR",
  "LAKSAR",
  "NARSAN",
  "ROORKEE",
  "BHIMTAL",
  "DHARI",
  "GHAT",
  "JOSHIMATH",
  "DEWAL",
  "OKHALKANDA",
  "RAMGARH",
  "LOHAGHAT",
  "BIRONKHAL",
  "BETALGHAT",
  "DWARIKHAL",
  "EKESHWAR",
  "KALJIKHAL",
  "KOTABAG",
  "KOT",
  "NAINIDANDA",
  "RAMNAGAR",
  "PAURI",
  "POKHRA",
  "RIKHNIKHAL",
  "DUGGADA",
  "YAMKESHWAR",
  "ZAHRIKHAL",
  "BERINAG",
  "DHARCHULA",
  "DIDIHAT",
  "GANGOLIHAT",
  "KANALICHINA",
  "MUNAKOT",
  "MUNSYARI",
  "KHIRSU",
  "AUGUSTMUNI",
  "JAKHOLI",
  "UKHIMATH",
  "BHILANGNA",
  "CHAMBA",
  "DEOPRAYAG",
  "JAKHNIDHAR",
  "JAUNPUR",
  "KIRTINAGAR",
  "NARENDRA NAGAR",
  "PRATAPNAGAR",
  "THAULDHAR",
  "PABAU",
  "PITHORAGARH",
  "JASPUR",
  "KASHIPUR",
  "KHATIMA",
  "BAJPUR",
  "SITARGANJ",
  "BHATWARI",
  "CHINYALISAUR",
  "DUNDA",
  "MORI",
  "NAUGAON",
  "PUROLA",
  "ASHOKNAGAR",
  "CHANDERI",
  "ISAGARH",
  "AMLA",
  "MEHGAON",
  "RAON",
  "BADA MALEHARA",
  "BARIGARH",
  "BIJAWAR",
  "BUXWAHA",
  "CHHATARPUR",
  "LAUNDI",
  "NOWGONG",
  "RAJNAGAR",
  "Dadra Nagar Haveli",
  "DAMAN",
  "DIU",
  "BAMORI",
  "SOHAGPUR",
  "DEPALPUR",
  "INDORE",
  "MHOW",
  "BADWARA",
  "BAHORIBAND",
  "DHEEMERKHEDA",
  "KATNI",
  "RITHI",
  "VIJAYRAGHAVGARH",
  "BARWAH",
  "BHAGVANPURA",
  "BHIKANGAON",
  "GOGAWAN",
  "KASRAWAD",
  "KHARGONE",
  "MAHESHWAR",
  "SEGAON",
  "ZIRANYA",
  "Babai Chichli",
  "CHAWARPATHA",
  "GOTEGAON",
  "KARELI",
  "NARSIMHAPUR",
  "SAINKHEDA",
  "NIWARI",
  "PRITHVIPUR",
  "AJAIGARH",
  "GUNOUR",
  "PANNA",
  "PAWAI",
  "SHAHNAGAR",
  "BADI",
  "BEGAMGANJ",
  "GAIRATGANJ",
  "BIAORA",
  "KHILCHIPUR",
  "NARSINGHGARH",
  "RAJGARH",
  "SARANGPUR",
  "zirapur",
  "AMARPATAN",
  "MAIHAR",
  "MAJHGAWAN",
  "NAGOD",
  "RAMNAGAR",
  "RAMPUR BAGHELAN",
  "SOHAWAL",
  "UNCHAHARA",
  "SEHORE",
  "BARGHAT",
  "CHHAPARA",
  "DHANAURA",
  "KAHNAPAS(GHANSAUR)",
  "KEOLARI",
  "KURAI",
  "LAKHNADON",
  "SEONI",
  "BEOHARI",
  "BURHAR",
  "GOHPARU",
  "JAISINGHNAGAR",
  "PICHHORE",
  "KUSMI",
  "MAJHAULI",
  "RAMPUR NAIKIN",
  "SIDHI",
  "SIHAWAL",
  "DEVSAR",
  "BADNAGAR",
  "GHATIYA",
  "KHACHAROD",
  "UJJAIN",
  "KARKELI",
  "MANPUR",
  "PALI",
  "VIDISHA",
  "JATARA",
  "JHABUA",
  "MAJHOULI",
  "BALDEOGARH",
  "JABALPUR",
  "KUNDAM",
  "MEGHNAGAR",
  "OBAIDALLAGANJ",
  "PALERA",
  "PANAGAR",
  "PATAN",
  "PETLAWAD",
  "RAMA",
  "RANAPUR",
  "SANCHI",
  "SHAHPURA",
  "SIHORA",
  "SILWANI",
  "THANDLA",
  "TIKAMGARH",
  "UDAIPURA",
];
